### ISSUE TITLE
Specifically doesn't detect "en" and "nl"

### ISSUE THREAD

**Issue by abejfehr** [webmil/text-language-detect#3]
Seemingly regardless of what string of text I put into `$l->detect()`, English and Dutch are never parts of the result. They seem to be present when I do `$l->languageExists("en")` or `$l->languageExists("nl")`, but are _never_ candidates.

Is something wrong with my `*.dat` files?

**Comment by abejfehr** [comment]
Actually, I can confirm that this doesn't work on my machine with PHP7, but does work on my colleague's PHP5.

**Comment by abejfehr** [comment]
I got it.

In the function `_unicode_block_name` comparisons are being made between hex strings and integers. This was possible in PHP5, but apparently not in PHP7.

Wrapping the strings in `hexdec()` seems to work.

**Comment by nichtich** [comment]
This bug report is a duplicate of #6 isn't it?

**Comment by abejfehr** [comment]
@nichtich Yeah, they're caused by the same problem, and was solved by the same fix. I'll close this one!
