### ISSUE TITLE
Stable release at packagist

### ISSUE THREAD

**Issue by nichtich** [webmil/text-language-detect#8]
The current version is only available as developer release without version number and it has a bug with PHP7. I could do some pull requests to improve test coverage but is this package still actively maintained?

**Comment by nichtich** [comment]
The original package at <http://pear.php.net/package/Text_LanguageDetect> includes fixes as well so we seem to have two unmaintained out-of-sync packages of the same name. I prefer to use the original version 1.0.0 from PEAR until maintainership has been clarified :

~~~json
{
  "repositories": [
    {
      "type": "pear", 
      "url": "https://pear.php.net/"
    }
  ],
  "require": {
    "pear-pear.php.net/Text_LanguageDetect": "1.0.0"
  }
}
~~~

@rwos has another fork, maybe he is willig to take over?

**Comment by rwos** [comment]
@nichtich our fork is just a collection of the fixes that lie around here on github - https://github.com/easybiblabs/text-language-detect/releases/tag/0.4.0 ([diff](https://github.com/webmil/text-language-detect/compare/master...easybiblabs:master)).

But thanks for the notice -  it seems https://github.com/pear/Text_LanguageDetect is in active development (again?). So maybe that's the version we should all switch to (I haven't looked at the diff yet).

**Comment by nichtich** [comment]
Yes, better ask @cweiske to release at packagist and then replace the clones with dummy packages that require the original and include a deprecation message:

https://packagist.org/packages/webmil/text-language-detect
https://packagist.org/packages/hugsbrugs/text-language-detect

Meanwhile this works to make use of the package in your project:

~~~
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/pear/Text_LanguageDetect"
    }       
  ],    
  "require": {
    "pear/Text_LanguageDetect": "dev-master",
~~~

**Comment by cweiske** [comment]
I did not see that the official package was not on packagist. It is now: https://packagist.org/packages/pear/text_languagedetect
